### ISSUE TITLE
Creating Facebook Cover

### ISSUE THREAD

**Issue by mahimamishra** [GroceriStar/social#10]
Our Facebook page needs a cover image. @atherdon  please create one so that I can upload it as soon as possible.

**Comment by atherdon** [comment]
https://github.com/GroceriStar/creative/tree/master/FBcovers

**Comment by mahimamishra** [comment]
We can use the first image.
Please try to put the logo of groceristar

**Comment by atherdon** [comment]
gotcha! will do it later and notify you with updates


On 06-Jun-2018 at 07:12 AM, Mahima Mishra wrote:


We can use the first image.
Please try to put the logo of groceristar

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/social/issues/10#issuecomment-394964851>,
or mute the thread
